#!/bin/bash
# Demo aplikasi monitoring harga pangan

echo "🎯 Demo Aplikasi Monitoring Harga Pangan Malang"
echo "=============================================="
echo ""
echo "📱 Aplikasi Streamlit dengan fitur:"
echo "   ✅ Judul: MONITORING REALTIME HARGA KOMODITAS PANGAN DI MALANG"
echo "   ✅ Side menu dengan st.radio untuk komoditas"
echo "   ✅ Dashboard interaktif dengan chart"
echo "   ✅ Pengembang: M Nasri AW, @2025"
echo ""
echo "📊 Komoditas yang tersedia:"
echo "   🌾 Beras berbagai kualitas"
echo "   🧅 Bawang Merah & Putih"
echo "   🌶️ Cabai Merah & Rawit"
echo "   🥩 Daging Ayam & Sapi"
echo "   🥚 Telur Ayam"
echo "   🧂 Gula Pasir"
echo "   🛢️ Minyak Goreng"
echo ""
echo "🚀 Untuk menjalankan aplikasi:"
echo "   ./run_app.sh"
echo "   atau"
echo "   streamlit run monitoring_pangan.py"
echo ""
echo "📈 Fitur aplikasi:"
echo "   - Pilih komoditas via radio button di sidebar"
echo "   - Tampilan harga real-time"
echo "   - Chart tren harga 7 hari"
echo "   - Tabel lengkap semua komoditas"
echo "   - Statistik harga rata-rata & tertinggi"
echo ""
echo "📂 File yang dibuat:"
echo "   ✅ monitoring_pangan.py - Aplikasi Streamlit utama"
echo "   ✅ requirements.txt - Dependencies"
echo "   ✅ run_app.sh - Script launcher"
echo "   ✅ README.md - Dokumentasi lengkap"
echo ""
echo "🎉 Aplikasi siap digunakan!"